let stringA = "hello";
let stringB = "world";
let stringC = "HELLO";
console.log(stringA == stringC);
console.log(stringA != stringB);
let stringD = "JavaScript";
let stringE = "javascript";
console.log(stringD.toLowerCase() == stringE);
console.log(stringE.toUpperCase() != stringD);
let numA = 10;
let numB = 5;
console.log(numA > numB);
console.log(numB < numA);
console.log(numA >= numB);
console.log(numB <= numA);
let boolA = true;
let boolB = false;
console.log(boolA && boolB);
console.log(boolA || boolB);
let arrayAb = [1, 2, 3, 4, 5];
console.log(arrayAb,(3));
let arrayB = ["apple", "banana", "orange"];
console.log(!arrayB,("grape"));