var stringA = "hello";
var stringB = "world";
var stringC = "HELLO";
console.log(stringA == stringC);
console.log(stringA != stringB);
var stringD = "JavaScript";
var stringE = "javascript";
console.log(stringD.toLowerCase() == stringE);
console.log(stringE.toUpperCase() != stringD);
var numA = 10;
var numB = 5;
console.log(numA > numB);
console.log(numB < numA);
console.log(numA >= numB);
console.log(numB <= numA);
var boolA = true;
var boolB = false;
console.log(boolA && boolB);
console.log(boolA || boolB);
var arrayAb = [1, 2, 3, 4, 5];
console.log(arrayAb, (3));
var arrayB = ["apple", "banana", "orange"];
console.log(!arrayB, ("grape"));
