var num1 = 10;
var num2 = 5;
var string1 = "hello";
var string2 = "world";
var bool1 = true;
var bool2 = false;
console.log(num1 > num2);
console.log(string1 == string2);
console.log(num1 <= num2);
//console.log(bool1 != bool2);
console.log(num1 + num2 == 15);
console.log(string1 != string2);
console.log(bool1 && bool2);
console.log(num1 - num2 > 10);
console.log(string1 < string2);
console.log(bool1 || bool2);
